- name: Wikijs
  hosts: wikijs
  tasks:
     - name: Update and upgrade apt packages
       become: true
       apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400  # One day

     - name: Preinstallation process for Docker
       become: true
       apt:
            name: "{{ item }}"
            state: latest
            update_cache: yes
       loop: 
            "{{ ['ca-certificates',
            'curl',
            'gnupg',
            'lsb-release'] }}"

     - name: Add Docker GPG-key
       become: true
       apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

     - name: Add Docker Repo
       become: true
       apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present

     - name: Update apt and install docker
       become: true
       apt:
            update_cache: yes
            name: "{{ item }}"
            state: latest
       loop:
            "{{ ['docker-ce',
            'docker-ce-cli',
            'containerd.io'] }}"

     - name: Install Docker Module for Python
       become: true
       pip:
            name: docker









