#!/usr/bin/env ansible-playbook

- name: Wikijs
  hosts: wikijs
  become: true
  tasks:
    - name: Create project directory
      file:
        path: /opt
        state: directory

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes

    - name: Preinstallation process
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - openssl
          - docker-compose
        state: latest

    - name: Add Docker GPG-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # TODO: change ubuntu to crossplatform ($lsb-release)
    - name: Add Docker Repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Create Wiki directory
      file:
        path: /etc/wiki
        state: directory

    - name: Check if DB secret already exists
      stat:
        path: /etc/wiki/.db-secret
      register: db_secret

    - name: Create DB secret
      shell:
        cmd: "openssl rand -base64 32 > /etc/wiki/.db-secret"
      when: db_secret.stat.exists == False

    - name: Copy configs to host
      copy:
        src: configs
        dest: /opt

    - name: Start wiki via Docker-Compose
      docker_compose:
        project_src: /opt/configs
