#!/usr/bin/env ansible-playbook

- name: Wikijs
  hosts: wikijs
  become: true
  tasks:
    - name: Create project directory
      file:
        path: /opt
        state: directory

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes

    - name: Preinstallation process
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - openssl
          - docker-compose


    - name: Add Docker GPG-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Create Wiki directory
      file:
        path: /etc/wiki
        state: directory

    - name: Check if DB secret already exists
      stat:
        path: /etc/wiki/.db-secret
      register: db_secret

    - name: Create DB secret
      shell:
        cmd: "openssl rand -base64 32 > /etc/wiki/.db-secret"
      when: db_secret.stat.exists == False

    - name: Copy configs to host
      copy:
        src: configs
        dest: /opt

    - name: Set logrotate for /var/log directory
      copy:
        src: /opt/configs/wiki_rotate.conf
        dest: /etc/logrotate.d
        remote_src: true

    - name: Set logrotate for Docker
      copy:
        src: /opt/configs/daemon.json
        dest: /etc/docker
        remote_src: true

    - name: Download node_exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.1.0/node_exporter-1.1.0.linux-amd64.tar.gz
        dest: /opt

    - name: Configuring node_exporter
      unarchive:
        src: /opt/node_exporter-1.1.0.linux-amd64.tar.gz
        dest: /opt
        remote_src: true

    - name: Setting node_exporter-service config
      copy:
        src: /opt/configs/node_exporter.service
        dest: /etc/systemd/system
        remote_src: true

    - name: Starting node_exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Start wiki via Docker-Compose
      docker_compose:
        project_src: /opt/configs
