version: "3.5"

networks:
  wikinet:
    name: wikinet

volumes:
  pgdata:
    name: pgdata

services:
  db:
    container_name: db
    image: "postgres:11"
    networks:
      - wikinet
    hostname: db
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_USER=wiki
      - POSTGRES_PASSWORD_FILE=/etc/wiki/.db-secret
    volumes:
      - /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro
      - pgdata:/var/lib/postgresql/data
  wiki:
    container_name: wiki
    image: ghcr.io/requarks/wiki:latest
    networks:
      - wikinet
    hostname: wiki
    restart: "unless-stopped"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASS_FILE=/etc/wiki/.db-secret
      - DB_USER=wiki
      - DB_NAME=wiki
    volumes:
      - /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro

  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - wikinet
    hostname: nginx
    restart: "unless-stopped"
    volumes:
      - ./nginx/wikijs.berizaryad.ru.conf:/etc/nginx/conf.d/wikijs.berizaryad.ru.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/berizaryad.ru.crt:/etc/ssl/certs/berizaryad.ru.crt:ro
      - ./nginx/berizaryad.ru.key:/opt/nginx/berizaryad.ru.key:ro
    ports:
      - "80:80"
      - "443:443"
